feat: more icons
yearn/yearn-assets pull request #286
Opened 2023-09-25 16:48 UTC by 0xBasically

- add crvUSD icon
- add curve yeth
- add base vault icons

2023-09-25 19:37 UTC, dudesahn requested changes
mostly just simplifying a few things

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0x69ACcb968B19a53790f43e57558F5E443A91aF22/logo-128.png
2 things

- should this be the purple icon? I saw that one on Curve
- purple logo or not, the CRV logo should be bottom-right. afaik it's only upper-right for tokens that have another asset needed to be displayed

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xBfAb6FA95E0091ed66058ad493189D2cB29385E6/logo-128.png
this is the wBETH canonical pool, should just be the wBETH logo with CRV in the bottom-right

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xa4c567c662349BeC3D0fB94C4e7f85bA95E208e4/logo-128.png
another canonical pool, just the main logo with CRV

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0x8272E1A3dBef607C04AA6e5BD3a1A134c8ac063B/logo-128.png
for all of these crvUSD pools, imo crvUSD should be smaller. the focus of the pool is the _other_ asset, as it's pairing with the base asset of crvUSD

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xBe426b0f37c112dd20d5866769c8034171567b31/logo-128.png
same comment as for DOLA

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xC2ADaD1Bd59a1DA3D35bd86cDb555694372f488F/logo-128.png
same comment as for DOLA

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xF5f33812c93C5f2Ae2F28c041eEb393212439502/logo-128.png
same comment as for DOLA

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xeCDd0cE505da71cd9dE855CD6804BA1e8C7bdB07/logo-128.png
same comment as for DOLA

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/1/0xfb5137Aa9e079DB4b7C2929229caf503d0f6DA96/logo-128.png
same comment as for DOLA

2023-09-25 19:37 UTC, dudesahn commented on icons/multichain-tokens/8453/0xF8f36Ab972f6fE3ae1f594595aEe1284E270d034/logo-128.png
is the center part of the wUSDR logo centered in the circle? I can't tell. ideally it would be, it's bugging me for some reason

2023-09-25 22:08 UTC, 0xBasically commented on icons/multichain-tokens/1/0x69ACcb968B19a53790f43e57558F5E443A91aF22/logo-128.png
good catch right on both

2023-09-27 13:26 UTC, dudesahn approved these changes

2023-09-27 13:39 UTC, merged